### ISSUE TITLE
dicom_numpy gives a 2D output when it is a 3D image

### ISSUE THREAD

**Issue by sotod** [innolitics/dicom-numpy#21]
Hi there, thanks for the very nice software. I have a question. In trying to convert a single dcm to numpy array 
I get an output with 2D while it is a 3D image --can you help ? 
thanks! 
david
[IM-0002-0005.dcm.zip](https://github.com/innolitics/dicom-numpy/files/5347933/IM-0002-0005.dcm.zip)
']  

import glob
import pydicom
import dicom_numpy
dicomlist = ['/Users/dsb/Downloads/Dicoms/IM-0002-0005
def extract_voxel_data(list_of_dicom_files):
    datasets = [pydicom.read_file(f) for f in list_of_dicom_files]
    try:
        voxel_ndarray, ijk_to_xyz = dicom_numpy.combine_slices(datasets)
    except dicom_numpy.DicomImportException as e:
        # invalid DICOM data
        raise
    return voxel_ndarray

outp = extract_voxel_data(dicomlist)

**Comment by johndgiese** [comment]
@sotod this looks like a bug, since I believe we should return 3D arrays even if there is a single slice! Thank you for reporting it. Someone on our Innolitics team will try to look into it at some point, although it may be a few weeks since we are pretty busy with client projects. If you send a PR I can try to review it quickly.

**Comment by sotod** [comment]
thanks for the response! sorry but don't know what PR is! can you clarify?
if submitted the code and the example data I used with my post
cheers
 david

**Comment by johndgiese** [comment]
@sotod ahh, sorry--- by "PR" I mean "Pull Request". It is a feature of GitHub, and it is the main way of contributing to open source code repositories. See https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request for more details.

**Comment by sotod** [comment]
my first PR in github! let's see how it went ;-), thanks for your help!!
David

**Comment by GraceAdams** [comment]
While investigating this PR, I noticed that the code does return a 3D array of shape (792, 792, 1), which is the expected behavior. I think the issue stems from a misunderstanding of the input format and the expected output.

This DICOM file is a mosaic image of 66 slices. The combine_slices function expects each file to be an individual slice. Currently we do not support the Siemens mosaic format. But if you would like to implement it, here is a reference (https://nipy.org/nibabel/dicom/dicom_mosaic.html) and we would be glad to review the code for you.
![dicom-image-example](https://user-images.githubusercontent.com/54726249/96755383-447e0b80-1398-11eb-8621-9847e952ed2e.png)

I can see in the DICOM header that there is a DICOM tag called source image sequence which contains references to the slices used to make this mosaic, but dicom_numpy does not interface with your PACS. You can see this here: https://dicom.innolitics.com/ciods/mr-image/general-reference/00082112
![dicom-source-image-sequence-example](https://user-images.githubusercontent.com/54726249/96755386-4516a200-1398-11eb-8a02-866dfbd13482.png)

I would recommend pulling the referenced SOP Instance UIDs from your PACS and inputting those into dicom_numpy instead.

I hope this helps.
