### ISSUE TITLE
why the pixel_array is transposed?

### ISSUE THREAD

**Issue by lyhyl** [innolitics/dicom-numpy#26]
https://github.com/innolitics/dicom-numpy/blob/edfa3644e631b874b6a755cc857c0cc3f2d0f686/dicom_numpy/combine_slices.py#L112
It gives a transposed result when I try to create an image from a voxel slice.

**Comment by jond01** [comment]
Hi, the reason for the transpose is to keep the returned `voxels` array in the standard indexing order.
Namely, the access to row `i`, column `j`, and plane `k` is with `voxels[i, j, k]` (rather than ~~`voxels[k, j, i]`~~).
If you have also channels (RGB for example) and want to access channel `c`, it is usually possible with `voxels[c, i, j, k]`, but it may depend on other attributes of your dicom dataset.

**Comment by lyhyl** [comment]
> Hi, the reason for the transpose is to keep the returned `voxels` array in the standard indexing order.
> Namely, the access to row `i`, column `j`, and plane `k` is with `voxels[i, j, k]` (rather than ~`voxels[k, j, i]`~).
> If you have also channels (RGB for example) and want to access channel `c`, it is usually possible with `voxels[c, i, j, k]`, but it may depend on other attributes of your dicom dataset.

thank you! it is a tradeoff.
